# fly.toml app configuration file generated for filmlim on 2024-11-04T08:27:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filmlim'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = false
  APP_ENV = 'production'
  APP_NAME = 'filmlim'
  APP_URL = 'https://filmlim.fly.dev/'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'postgres'
  DB_HOST = 'aws-0-ap-northeast-1.pooler.supabase.com'
  DB_PORT = '6543'
  DB_USERNAME = 'postgres.fxlosjrhzehvwasenolq'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[mounts]
  source = 'storage_vol'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
